language: php
php: "7.0"
services: 
    - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - export DATABASE_URL="travis_ci_test"
  - cd bin && ./setupSQL.sh
script: echo Done 