language: php 
php: 
  '7.0'
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.cloud.gov
  username: john.r.lepird.mil@mail.mil
  password:
    secure: OR0ZSUVrMxRCsDfsdnFcRZc0ms+QXqr944X3LTXgZk71auVe4S5k1v7Ndg8Fv0OJBwGJ2XefRhKk4j85fX8V7fJkgLvsZ6OCRPI2Qo7FMRwh8snJJexApZyFRWqmqSsc9UebEHt/WUQNsR0Fy7I0X9i2EwiKbphuQILKDvDcz3DILucBAhOJRRqVgMOMlVPEPOMpBgocRQsXnLZKaTqDfsGKrTeUMLXJl0UhQ6grocz0WQxc3tLx/zIJmAIcKu8fxXoip55CbPNQP+XJB3LPFAcEt5gAMeybyp/9dfPFICISGNZ/lmN/JpDTg7SXF22I8QlRpYa5RFro1VG/JSaBWi2BVlyAQyItxARpUpy2O0LbUqEICZmV+nEWYlHYyBWV664o4GqA4WDFjKZnveenbgPfdB03Kip23lYIdBBturOzyD8PM2sLhNGjAWMbBCdoLxlbVzajoO1vu1Z6MrmcxeaL8DZDMtVumM67WPMMy76W+EhnNUmIghp1Db2JtdBln4juZUbRQCSV/Ibsn8LKpzzDj18vqDs1aVKvTBqslUlzWt1yf8A2Sajr3d+iWYvGmKj8Ce4me271/LwGcIXmuqqNJaPDTi42moI8vUbpRObRZkFAWnsbTpZbsfbQ7QQ5C/nBlee6gHfxMaRxRKQBIcsvfKRcc4gp+KijiafEc/A=
  organization: sandbox-mil
  space: john.r.lepird.mil
  on:
    repo: jlepird/next-gen-assignments
